/gps_slam_converter:
  ros__parameters:
    std_point_slam_x1: 871
    std_point_slam_y1: 291
    std_point_slam_x2: 1106
    std_point_slam_y2: 661
    slam_map_width: 1482
    slam_map_height: 1473
    slam_map_shift: 0
    slam_map_resolution: 0.05
    std_point_lon1: 127.1241
    std_point_lat1: 37.46604
    std_point_lon2: 127.1237
    std_point_lat2: 37.46606
    start_point_lon: 127.124136
    start_point_lat: 37.465932
    end_point_lon: 127.124107
    end_point_lat: 37.465798
