/gps_slam_converter:
  ros__parameters:
    std_point_slam_x1: 313
    std_point_slam_y1: 528
    std_point_slam_x2: 1630
    std_point_slam_y2: 1017
    slam_map_width: 2377
    slam_map_height: 1258
    slam_map_shift: 0
    slam_map_resolution: 0.05
    std_point_lon1: 128.8579836
    std_point_lat1: 35.1576298
    std_point_lon2: 128.858333
    std_point_lat2: 35.15818
    start_point_lon: 128.858009083
    start_point_lat: 35.157430158
    end_point_lon: 128.858870603
    end_point_lat: 35.158056682
